---
title: "pivoting the dataframe"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
library(tidyverse)
library(gdxtools)
```

```{r}
path <- "C:/Users/modin/Desktop/Ettore/UNIVERSITA/ECC_GAMS/ECC-Project/witchmodel"
#path <- "C:/Users/modin/Desktop/Ettore/UNIVERSITA/ECC_GAMS/RICE/RICE50x_v1_portable/results"

files <- list.files(path,pattern = ".gdx")
myfiles <- file.path(path, files)
myfiles = myfiles %>% str_subset(pattern = "results.*\\.gdx")
dataset <- read.csv(file="curve2.csv")
head(dataset)
colnames(dataset)<-c("X","n","deg0","deg4")

dataset<- dataset[,2:4] %>% pivot_longer(cols=!n)
head(dataset)

mod_lit <- data.frame(dataset[2],dataset[1],dataset[3])
head(mod_lit)
write.gdx("data_mod_lithium.gdx",list(trade_poly_lit=mod_lit), compress=F)
```


```{r}
path <- "C:/Users/modin/Desktop/Ettore/UNIVERSITA/ECC_GAMS/ECC-Project/witchmodel/modules"
files <- list.files(path,pattern = ".gdx")
myfiles <- file.path(path, files)
myfiles = myfiles %>% str_subset(pattern = "results.*\\.gdx")
dataset <- read.csv(file="curve2.csv")
head(dataset)


head(dataset)
colnames(dataset)<-c("X","n","deg0","deg4")

n = unique(dataset$Region)

dataset<- dataset[,2:4] %>% pivot_longer(cols=!n)
head(dataset)

mod_lit <- data.frame(dataset[2],dataset[1],dataset[3])
head(mod_lit)
#write.gdx("data_battery.gdx",list(increase_price_rare_material=df), compress=F)
```

# battery cost override
```{r}
t = seq(1,30)
b0 = 803.48
bf = 90

battery_cost_vals = round((b0-bf)*exp(-5/3*(t-1))+bf,2)
battery_cost = data.frame(t=t,value=battery_cost_vals)

ggplot(battery_cost,aes(x=t,y=battery_cost_),type="b",pch = 16)+ geom_line() 

write.gdx("data_battery_updated.gdx", list(battery_cost = battery_cost), compress = FALSE)
```

```{r}
t = seq(1,30)
p_rmb = 0.15



## fino al 2020 uguale
## spike 2025-2040
## 2040-2060 return to 1 new tec
t = seq(1,15)
growth = (1-exp(-5/30*(t)))
growth2 = 1-(1-exp(-5/30*(t)))

t = seq(1,30)
plot(t,c(growth,growth2))


inc_prmat =  p_rmb*growth_rate
plot(t,inc_prmat,type="l")
battery_final = (1+inc_prmat*0.5)*battery_cost_vals
plot(t,battery_final,type="l")
```


```{r}
df = data.frame(t,value=round(inc_prmat,2))
df
gdxdata=write.gdx("data_battery.gdx",list(increase_price_rare_material=df), compress=F)
mygdx  =gdx("data_battery.gdx")
```



```{r}
no_lit <- c("canada","jpnkor","mexico","india","indonesia","mena","sasia","seasia","te","europe", "usa", "brazil", "ssa")
lit = setdiff(no_lit, n)
no_lit_maybe <- c("europe", "usa", "brazil", "ssa")
no_cob <- c("europe", "jpnkor", "mexico", "usa", "brazil", "india", "indonesia", "sasia","laca")
no_cob_maybe = "laca"
cob = setdiff(no_cob, n)
lit_cob <- c("oceania", "china", "southafrica")



#is_included <- setdiff(as.vector(countrys$V1), all)

countrys <- unique(c(no_lit, no_lit_maybe, no_cob, no_cob_maybe, lit_cob))
df <- data.frame(
  n = countrys,
  no_lit = as.numeric(countrys %in% no_lit),
  no_cob = as.numeric(countrys %in% no_cob),
  lit_cob = as.numeric(countrys %in% lit_cob)
)

df
#dataset <- df %>% pivot_longer(cols = !n)
dataset
colnames(dataset) <- c("n", "", "Value")
write.gdx("data_materials.gdx", list(materials = dataset), compress = FALSE)
# crea dataframe con i valori moltiplicativi
# ogni nazione troverà il suo fattore moltiplicativo di prezzo
increment <- c(0.5, 0.3, 0.1, 0.6, 1)
binary <- dataset[dataset$n == "canada", 3]$Value
val <- sum(increment * binary)
```


